# Generated by Django 5.2.14 on 2026-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceDayRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('app_recorded', 'App Recorded'), ('provider_reconciled', 'Provider Reconciled'), ('technical_miss', 'Technical Miss'), ('unverified_absence', 'Unverified Absence')], max_length=50)),
                ('reconciliation_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
