# Generated by Django 5.2.14 on 2026-05-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherence', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencedayrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_day_records', to='users.patientuser'),
        ),
        migrations.AddField(
            model_name='symptomrecord',
            name='adherence_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_records', to='adherence.adherencedayrecord'),
        ),
    ]
