# Generated by Django 5.2.14 on 2026-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencedayrecord',
            name='reconciliation_method',
            field=models.CharField(blank=True, choices=[('home_visit', 'Home Visit'), ('dot_order', 'DOT Order'), ('send_message', 'Send Message')], max_length=50, null=True),
        ),
    ]
