# Generated by Django 5.2.14 on 2026-05-28 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0003_adherencedayrecord_reconciliation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencedayrecord',
            name='dose_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
