# Generated by Django 5.2.14 on 2026-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0004_adherencedayrecord_dose_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherencedayrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('app_recorded', 'App Recorded'), ('provider_reconciled', 'Provider Reconciled'), ('technical_miss', 'Technical Miss'), ('unverified_absence', 'Unverified Absence')], default='technical_miss', max_length=50),
        ),
    ]
