# Generated by Django 5.2.14 on 2026-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0005_alter_adherencedayrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencedayrecord',
            name='video_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
    ]
