# Generated by Django 5.2.14 on 2026-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0006_adherencedayrecord_video_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherencedayrecord',
            name='video_endpoint',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adherencedayrecord',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
