# Generated by Django 5.2.14 on 2026-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_regimen_days', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('heart_quota', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tier', models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')])),
                ('penalty_given', models.IntegerField(default=0)),
                ('reverted', models.BooleanField(default=False)),
            ],
        ),
    ]
