# Generated by Django 5.2.14 on 2026-05-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherence', '0002_initial'),
        ('gamification', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstats',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.patientuser'),
        ),
        migrations.AddField(
            model_name='penaltyevent',
            name='adherence_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_event', to='adherence.adherencedayrecord'),
        ),
        migrations.AddField(
            model_name='penaltyevent',
            name='patient_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_events', to='gamification.patientstats'),
        ),
    ]
