# Generated by Django 5.2.14 on 2026-05-27 08:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstats',
            name='current_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientstats',
            name='month3_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientstats',
            name='regimen_start_date',
            field=models.DateField(default=datetime.date(2026, 5, 27)),
            preserve_default=False,
        ),
    ]
