# Generated by Django 5.2.14 on 2026-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_patientstats_current_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstats',
            name='forgiveness_quota_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientstats',
            name='forgiveness_quota_used_this_month',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='penaltyevent',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1 — Soft Warning'), (2, 'Tier 2 — Partial Reset A'), (3, 'Tier 3 — Partial Reset B'), (4, 'Tier 4 — Full Reset + Escalation')]),
        ),
    ]
